version: '3'

volumes:
  payment_service_local_postgres_data: { }
  payment_service_local_postgres_data_backups: { }
  prometheus-data: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: payment_service_local_django
    container_name: payment_service_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: payment_service_production_postgres
    container_name: payment_service_local_postgres
    volumes:
      - payment_service_local_postgres_data:/var/lib/postgresql/data:Z
      - payment_service_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  #  docs:
  #    image: payment_service_local_docs
  #    container_name: payment_service_local_docs
  #    platform: linux/x86_64
  #    build:
  #      context: .
  #      dockerfile: ./compose/local/docs/Dockerfile
  #    env_file:
  #      - ./.envs/.local/.django
  #    volumes:
  #      - ./docs:/docs:z
  #      - ./config:/app/config:z
  #      - ./payment_service:/app/payment_service:z
  #    ports:
  #      - "9000:9000"
  #    command: /start-docs

  redis:
    image: redis:6
    container_name: payment_service_local_redis

  celeryworker:
    <<: *django
    image: payment_service_local_celeryworker
    container_name: payment_service_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: payment_service_local_celerybeat
    container_name: payment_service_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celerybeat

  flower:
    <<: *django
    image: payment_service_local_flower
    container_name: payment_service_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  prometheus:
    image: prom/prometheus:v2.30.3
    restart: 'no'
    ports:
      - 9090:9090
  #    network_mode: host

  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - 3060:3000
