global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:8006']
