# Generated by Django 4.0.8 on 2022-12-20 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('business_name', models.CharField(max_length=255)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('contact_person_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name_plural': 'Service Providers',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('ServiceProvider'), models.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.FloatField()),
                ('tracking_id', models.PositiveBigIntegerField(default=0)),
                ('bank_ref_no', models.PositiveBigIntegerField(default=0)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('order_status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Failure'), (3, 'Aborted'), (4, 'Invalid'), (5, 'Timeout')], default=0)),
                ('payment_mode', models.PositiveIntegerField(choices=[(1, 'IVR'), (2, 'S'), (3, 'EMI'), (4, 'Credit Card'), (5, 'Net banking'), (6, 'Debit Card'), (7, 'Cash Card'), (8, 'UPI'), (9, 'Wallet')], default=0)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('application_fk', models.ForeignKey(blank=True, db_column='application_fk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_application', to='users.applicationmaster')),
                ('service_provider_fk', models.ForeignKey(blank=True, db_column='service_provider_fk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_service_provider', to='payment_gateway.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('Transaction'), models.Model),
        ),
    ]
